### ISSUE TITLE
Chat format?

### ISSUE THREAD

**Issue by brucethemoose** [LargeWorldModel/LWM#1]
Hello, what is the chat format for the chat models?

Llama?

**Comment by wilson1yan** [comment]
It's similar to the Vicuna chat format, with a slight change in system prompt. An example of it can be found in the eval file: https://github.com/LargeWorldModel/LWM/blob/9aaaa1e864bfcf31b66028e782395a22f4817535/scripts/eval_needle.py#L48

i.e. `You are a helpful assistant: USER: <user_input> ASSISTANT: `
