### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [LargeWorldModel/LWM#11]
Hi,
Great work on LWM! I noticed the weights are licensed under the Apache license but derived from Llama 2, do both the Llama 2 license and the Apache license apply to the weights?
Thanks!

(Related to #10)

**Comment by justinthelaw** [comment]
Hi, I'm also curious about this. It seems the licenses are a bit conflicting, or rather this GH says Apache 2.0 but HF says LLaMA.

**Comment by lhao499** [comment]
Hi, this codebase is licensed under Apache 2.0. The models, since are derivatives of Llama 2, are under the license of Llama 2. 
Will make this more clear in documentation.
