### ISSUE TITLE
How long to train the model?

### ISSUE THREAD

**Issue by HaoranZhuExplorer** [LargeWorldModel/LWM#12]
Thank you for your contribution! Amazing performance! I just wonder the computational requirements for training such world models, e.g., how many GPUs and how long you need to train it?

**Comment by lhao499** [comment]
Compute details and training time are shown in Appendix F and Figures 10-11 in the LWM paper: [https://arxiv.org/abs/2402.08268](https://arxiv.org/abs/2402.08268)

**Comment by HaoranZhuExplorer** [comment]
> Compute details and training time are shown in Appendix F and Figures 10-11 in the LWM paper: https://arxiv.org/abs/2402.08268

My bad, I didn't see these details. Thank you for your response!

**Comment by HaoranZhuExplorer** [comment]
solved
